// import filmes from "./filmes.json" assert { type: "json" };

const filmes_list = [
  {
    titulo: "Homem-Aranha",
    subTitulo: "Sem Volta para Casa",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/DYkDjvdlR4asxPTaVmk_wsgcKkoTNXfEY6q_U9JbR69gVbmw5fua2w6qR3637OpYVSu-LJNU7RVO0P-uOok=w240-h480-rw",
  },
  {
    titulo: "Deadpool 2",
    subTitulo: "",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/48OaU2sbdQexOUJbUOxE9mzIKDWMKap-2Y7MWDkrWih8UfAolckCvL0zEXBI_6gaZxbX=w240-h480-rw",
  },
  {
    titulo: "Top Gun",
    subTitulo: "Ases Indomavel",
    censura: "livre",
    categoria: "ação",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/Rb1peOLtiQWHXLgSPQf5csKlesD3BCzDHULKg9OoSDpQnVEbVoNQ1leEfAf2997sA0SqK5XXsqYJVkB3Gw=w240-h480-rw",
  },
  {
    titulo: "Sonic 2",
    subTitulo: "O Filme",
    censura: "livre",
    categoria: "fantasía",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/iamOvwpKncypLUAofASDZZXh_XCidWEvB3-jvCOXaGOChRSTYHctMPLQjy3n6L9g11HU2r-APxxDEBr3Ofo=w240-h480-rw",
  },
  {
    titulo: "Animais Fantásticos",
    subTitulo: "Os Segredos de Dumbledore",
    censura: "livre",
    categoria: "fantasía",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/cB-ujm8BoBkwuu4g_i18vyUQJp34S15UB4VF3WzI-bv_wgVkaGqWcr_7lTJDBJNt8aNNv8_4EaImfEySdVs=w240-h480-rw",
  },
  {
    titulo: "Batman",
    subTitulo: "",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/6R0ekUXQ2A4uPJ1Jn3b7u7Jo0j08kaqMtZ85Pw0DEa9WP6JcgloIAlkK4zhRDsxttq22WEkAoCaQz8cDAqVw=w240-h480-rw",
  },
  {
    titulo: "Jurassic World",
    subTitulo: "Dominion",
    censura: "livre",
    categoria: "ficção cientifica",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/SLqpYz75g14oLEIoy74Zrvtz_tJfdWuY1FynGcN2L-ad0XmuNMJ6JWCBFRyGudxwFZO8HOD0d-wAgM7kkL92=w240-h480-rw",
  },
  {
    titulo: "Morbius",
    subTitulo: "",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/cO0EQB5MqWrh5wQf3P2k52si2RaJKq3chGbnZ5XA4bWl3slVud02vlpRXXk4bTHFaKRK8HxqlVD1GExrlIk=w240-h480-rw",
  },
  {
    titulo: "Venom",
    subTitulo: "",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/pDTtHt8svIccbDuuqDSZpyK4_mJCbD0hL2UdgDX7yI3zM55KtitYEDfEDPxPi3THEKJB=w240-h480-rw",
  },
  {
    titulo: "Shazam!",
    subTitulo: "",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/GNe7re9RcTtOQKiSs7cECt_aTohEgMB-cMwDlaz8Bncpsymmz-sMc8AQ68io5whgw92QiiFgEnCg3MDR01dB=w240-h480-rw",
  },
  {
    titulo: "Liga da Justiça!",
    subTitulo: "Zack Snyder",
    censura: "livre",
    categoria: "super heróis",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/5KnPKEKrckelL02GhssjahM7_gEB8dE1TrI-swpWzgrwTt1U49qdSRaQQA3d4E6A_6J16eagpmkifPcWhN0=w240-h480-rw",
  },
  {
    titulo: "The Black Phone",
    subTitulo: "",
    censura: "livre",
    categoria: "terror",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/WfxldKxE7d6L088clgZHApfj2j-dp3PaBgmjPWUZNh3JG-vWQl2Z8oxKF7AgBOHKuYJp7FDRXxQ65X-VLQ=w240-h480-rw",
  },
  {
    titulo: "Rubikon",
    subTitulo: "",
    censura: "livre",
    categoria: "ficção cientifica",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/JyosqVzpbyUxUwrt-_hpKlTlgWxJLNHWQKZqSTw3JHcj4-5ajuDuulGBp3lAfQIJHtF7RvK89G13597t6GoL=w240-h480-rw",
  },
  {
    titulo: "Interstellar",
    subTitulo: "",
    censura: "livre",
    categoria: "ficção cientifica",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/em2griqrHoxmxEss_WM5Fi2iqSEKrEfLNAltjX54lREOR0nz0du__KuSi2bA_YNjS4w=w240-h480-rw",
  },
  {
    titulo: "A Origem",
    subTitulo: "",
    censura: "livre",
    categoria: "ficção cientifica",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/XSiqk-Szslzm7pKddsewFcWgPLjMh0MmOqqN6-22fDUDxdOBuMRuRT-Sr2e-KlzNZ8hRlCzorAjQ4WR72r-r=w240-h480-rw",
  },
  {
    titulo: "Dunkirk",
    subTitulo: "",
    censura: "livre",
    categoria: "historia",
    priceResol: [
      { resolucao: "720p", price: 10 },
      { resolucao: "1080p", price: 25 },
      { resolucao: "4K", price: 35 },
    ],
    img: "https://play-lh.googleusercontent.com/o1tf2JchOTaE-OlKr5VTuAqsxnK7LkrbK0rAFL1uO9t12Mcgm6AJgDdxJmPRN3V0hkI=w240-h480-rw",
  },
];
